apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    logLevel: {{ .Values.conf.logLevel }}
    logFormat: {{ .Values.conf.logFormat }}
    route:
      routes:
      - match:
{{- range .Values.conf.recievers }}
        - receiver: {{ .name }}
{{- end }}
    receivers:
{{- range .Values.conf.recievers }}
    - name:  {{ .name }}
      {{ .type }}: 
      {{- toYaml .config| nindent 8}}
{{- end }}
{{- if .Values.addons.loki.enabled }}
  fluent-bit.conf: |
    [Service]
      Log_Level    info
      Parsers_File    parsers.conf
    [Input]
      Name    tail
      Buffer_Chunk_Size    2M
      Buffer_Max_Size    5M
      Path   {{.Values.addons.loki.target_file}}
      DB    /fluent-bit/tail
      Mem_Buf_Limit    20MB
      Parser    json
      Tag    event.*
    [Filter]
      Name    modify
      Match   event.*
      Add    cluster   {{.Values.clustername}}
    [Output]
      Name    loki
      Match    event.*
      host    {{.Values.addons.loki.host}}
      port    {{.Values.addons.loki.port}}
      Labels job=event, $cluster, $metadata['name'], $metadata['namespace'], $type, $reason
      auto_kubernetes_labels on
  parsers.conf: |
    [PARSER]
      Name   json
      Format json
      Time_Key time
      Time_Format %d/%b/%Y:%H:%M:%S %z
{{- end }}