apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-event-exporter.serviceAccountName" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-event-exporter.serviceAccountName" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes-event-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.additionalRbacs -}}
---

{{- end -}}
